version: '3.4'

services:
  webapp:
    build: . 
    image: docker-nginx
    container_name: docker-nginx
    restart: always
    environment: 
      - PORT=8080
    ports: 
      - "8080:8080"
    # expose:
    #   - 5001
    volumes: 
      - ./src:/app
      - ./docker:/docker  
 